### ISSUE TITLE
How to reproduce "Boston Light Swim" for different geography

### ISSUE THREAD

**Issue by robragsdale** [ioos/notebooks_demos#172]
I have an idea for a notebook to predict water temperatures around Hatteras Island and in Pamilico sound to help a sea turtle stranding network anticipate water temperatures dropping below 50°F that can cause a "cold-stunned event" which is when sea turtles become unable to swim and wash ashore.

**Comment by ocefpaf** [comment]
@robragsdale in theory you should be able to change the bounding box and just run it. However, there are many moving parts in that notebook and I believe it won't be that simple.

We should start from the latest, not merged yet, version form #130 

Do you have the bounding box and times for this example so I can try to put an example together for you?

**Comment by robragsdale** [comment]
@ocefpaf the bbox [-75.42, 35.12, -75.33, 35.48] for start: 2016-01-04 00:00:00 stop: 2016-01-07 00:00:00.  Thanks for helping with an example.

**Comment by ocefpaf** [comment]
@robragsdale here is my first attempt:

http://nbviewer.jupyter.org/gist/ocefpaf/4b5e261dc0a6603ef6bd194c87d94809?flush_cache=true

Note that I did not use `pyoos` to find SOS data because I wanted to create a `100%` catalog version of this. (I could not find NDBC nor CO-OOPS buoys anyways.)

Note that there is not much to work with with those constraints.

Gridded data:
- http://oos.soest.hawaii.edu/thredds/dodsC/hioos/satellite/dhw.html
- http://thredds.aoos.org/thredds/dodsC/G1_SST_GLOBAL.nc.html
- http://oos.soest.hawaii.edu/thredds/dodsC/hioos/model/atm/ncep_global/NCEP_Global_Atmospheric_Model_best.ncd.html
- http://tds.maracoos.org/thredds/dodsC/SST-Seven-Agg.nc.html
- http://oos.soest.hawaii.edu/thredds/dodsC/pacioos/hycom/global.html

Trajectory data (glider):
- http://data.ioos.us/thredds/dodsC/deployments/drudnick/sp066-20151217T1624/sp066-20151217T1624.nc3.nc.html
- http://data.ioos.us/thredds/dodsC/deployments/drudnick/sp065-20151001T1507/sp065-20151001T1507.nc3.nc.html

**Comment by rsignell-usgs** [comment]
Since this goal was to **predict** water temperatures, how about the last 5 days and next 3 days.  That should at least turn up a few of the same forecast models we got in the Boston Light Swim example

**Comment by ocefpaf** [comment]
With -5 + 3 (start: 2017-01-13 00:00:00 and stop: 2017-01-21 00:00:00) we get:

grid:
- http://oos.soest.hawaii.edu/thredds/dodsC/pacioos/hycom/global.html
- http://oos.soest.hawaii.edu/thredds/dodsC/hioos/model/atm/ncep_global/NCEP_Global_Atmospheric_Model_best.ncd.html
- http://geoport-dev.whoi.edu/thredds/dodsC/coawst_4/use/fmrc/coawst_4_use_best.ncd.html


unknown:
- http://www.smast.umassd.edu:8080/thredds/dodsC/FVCOM/NECOFS/Forecasts/NECOFS_GOM3_FORECAST.nc.html

The last one is not recognized as gridded data because its `cdm_data_type` is `any`.

**Comment by rsignell-usgs** [comment]
@ocefpaf, the last one is NECOFS, UGRID-compliant.  

We should be picking up Ruoying's Forecast model: 
http://omgsrv1.meas.ncsu.edu:8080/thredds/catalog/fmrc/us_east/catalog.html?dataset=fmrc/us_east/US_East_Forecast_Model_Run_Collection_best.ncd
but I guess it's not in the IOOS catalog for some reason.   
Who should be notified at SECOORA to add
http://omgsrv1.meas.ncsu.edu:8080/thredds/catalog/fmrc/us_east/catalog.html
to their list of THREDDS endpoints to crawl?

I have added it to gamone's CSW in the meantime.  Can you try again and see if you pick it up?

**Comment by robragsdale** [comment]
@rsignell-usgs I think Vembu is the right person to contact first about adding this to their THREDDS call.  I can email him today about it.

**Comment by robragsdale** [comment]
[Ruoying's Forecast model](http://omgsrv1.meas.ncsu.edu:8080/thredds/catalog/fmrc/us_east/catalog.html?dataset=fmrc/us_east/US_East_Forecast_Model_Run_Collection_best.ncd) will be added to SECOORAs THREDDS server.  Vembu is working on this.

**Comment by rsignell-usgs** [comment]
@lukecampbell , @mwengren , this should be just one extra line in a config file somewhere, like
https://github.com/USGS-CMG/usgs-cmg-portal/commit/893cf030fee0eaadaa4e8fff1655fbfbd0be8ed6
shouldn't it?

**Comment by rsignell-usgs** [comment]
@lukecampbell , @mengren, are we tracking the repos where the RAs keep their WAF scripts?

I was just hoping that instead of complaining about a thredds catalog not being harvested, I could just go a github repo, find the WAF script that SECOORA is using, click the pencil icon, add the thredds endpoint, and submit a PR.

**Comment by lukecampbell** [comment]
I know I heard of that idea, but I don't think it's been implemented by anyone.

**Comment by rsignell-usgs** [comment]
@robragsdale , something to discuss at the DMAC meeting!   
All the regions should have their WAF scripts on github!

**Comment by mwengren** [comment]
@rsignell-usgs @robragsdale This issue got lost in the inbox amidst so many others.... so I made an attempt to get people to do this but there was limited response.  At the moment, we have one example from NERACOOS here: https://github.com/ioos/catalog/tree/master/waf_generation_scripts, but any other data providers are more than welcome to submit their WAF generation scripts to this repo.

**Comment by jbosch-noaa** [comment]
Perhaps  we should convert one or more of these script to a pretty notebook for the [Data Demo Center](https://ioos.github.io/notebooks_demos/). 
@mwengren ? @ocefpaf ? Whatcha think?

We could also put a link to the above repo folder on the "Other Resources" side bar

**Comment by ocefpaf** [comment]
> @ocefpaf ? Whatcha think?

I am not familiar with those scripts to answer that. I will take a look and see if that makes sense. @rsignell-usgs and @mwengren are definitely more qualified than me in that regard.

**Comment by rsignell-usgs** [comment]
Well, I not sure these are appropriate for notebooks since they are meant to be run by data managers, and usually in a cron job.

**Comment by jbosch-noaa** [comment]
Yeah ... when talking to @mwengren about it I agree.  Is there another place where you think a link to this repo folder might be helpful?

**Comment by ocefpaf** [comment]
We have a tentative notebook for this issue in #189 but that is stalled (and closed) due to a failed search. We can re-try this in the future if the region/time-span for the search are changed. Closing it for now.
