### ISSUE TITLE
Visualization of IOOS Regional Models 

### ISSUE THREAD

**Issue by jbosch-noaa** [ioos/notebooks_demos#284]
@ocefpaf  - This Issue may be broken into separate issues but it begins the conversation around an inventory project for the two of us that includes creating visualization notebook (s) for individual or groups of IOOS Regional Models.

Here is some guidance from @dpsnowden : 

Build off the model data comparison notebook work that Filipe did for SECOORA

Basic goals
1. Simple plot of the domain (Mesh and extent) See the COMT project page for a good example. [Figure 1ab](https://ioos.us/comt/projects/gom_hypoxia)
2. Plot of one field (SST, SSH etc)
3. Simple stats on characteristics of the model (resolution, grid type, vertical levels, time step)
4. Check to see if model is available on Regional Portal
5. Check to see if model is registered in IOOS Catalog

Top Priority
1. SECOORA/NCSU [CNAPS](http://omgsrv1.meas.ncsu.edu:8080/CNAPS/)
2. NERACOOS/UMAS Dartmouth [NECOFS](http://fvcom.smast.umassd.edu/necofs/)
3. MARACOOS Espresso
4. WCOFS
5. Southern California 3km ROMS YiChao
6. OSU ROMS
7. MARACOOS/Stevens Institute NYHOPS

**Comment by jbosch-noaa** [comment]
@ocefpaf - Where are you on any of these notebooks?

**Comment by ocefpaf** [comment]
I just pushed the first one today in
https://github.com/ioos/notebooks_demos/pull/303

I have two more that I'm planning to push next week.

On Mar 8, 2018 16:35, "Jennifer Bosch" <notifications@github.com> wrote:

@ocefpaf <https://github.com/ocefpaf> - Where are you on any of these
notebooks?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/ioos/notebooks_demos/issues/284#issuecomment-371598741>,
or mute the thread

**Comment by ocefpaf** [comment]
Just put together a to do list to help us tackle this issue.

- [X] Build off the model data comparison notebook work that Filipe did for SECOORA (done in #303 )
- [ ] Simple plot of the domain (Mesh and extent) See the COMT project page for a good example. [Figure 1ab](https://ioos.us/comt/projects/gom_hypoxia)
- [ ] Plot of one field (SST, SSH etc)
- [ ] Simple stats on characteristics of the model (resolution, grid type, vertical levels, time step)
- [ ] Check to see if model is available on Regional Portal
- [ ] Check to see if model is registered in IOOS Catalog

**Comment by ocefpaf** [comment]
Because of items 4-5 we should start from hardcoded endpoints for those models, here is what I have so far:

- [X] SECOORA/NCSU CNAPS: http://thredds.secoora.org/thredds/dodsC/SECOORA_NCSU_CNAPS.nc.html
- [ ] NERACOOS/UMAS Dartmouth NECOFS: ?
- [ ] MARACOOS ESPRESSO: ?
- [ ] WCOFS: http://data.oceansmap.com/thredds/dodsC/EDS/WCOFS
- [ ] Southern California 3km ROMS YiChao: ?
- [ ] OSU ROMS: ?
- [X] MARACOOS/Stevens Institute NYHOPS: http://colossus.dl.stevens-tech.edu:8080/thredds/complete_latest.html?dataset=complete_latest

---
For NECOFS, http://www.smast.umassd.edu:8080/thredds/dodsC/FVCOM/NECOFS/Forecasts, we have:

- [NECOFS_FVCOM_OCEAN_BOSTON_FORECAST](http://www.smast.umassd.edu:8080/thredds/dodsC/FVCOM/NECOFS/Forecasts/NECOFS_FVCOM_OCEAN_BOSTON_FORECAST.nc.html)
- [NECOFS_FVCOM_OCEAN_HAMPTON_FORECAST](http://www.smast.umassd.edu:8080/thredds/dodsC/FVCOM/NECOFS/Forecasts/NECOFS_FVCOM_OCEAN_HAMPTON_FORECAST.nc.html)
- [NECOFS_FVCOM_OCEAN_MASSBAY_FORECAST](http://www.smast.umassd.edu:8080/thredds/dodsC/FVCOM/NECOFS/Forecasts/NECOFS_FVCOM_OCEAN_MASSBAY_FORECAST.nc.html)
- [NECOFS_FVCOM_OCEAN_SCITUATE_FORECAST](http://www.smast.umassd.edu:8080/thredds/dodsC/FVCOM/NECOFS/Forecasts/NECOFS_FVCOM_OCEAN_SCITUATE_FORECAST.nc.html)

Should we select one of those or should we work with all of those?
I prefer the former otherwise the notebook will be 50% FVCOM and 50% other models.

---
For ESPRESSO, http://tds.marine.rutgers.edu/thredds/dodsC/roms/espresso/2013_da, we have:

- [ESPRESSO_Real-Time_v2_History_Best](http://tds.marine.rutgers.edu/thredds/dodsC/roms/espresso/2013_da/his/ESPRESSO_Real-Time_v2_History_Best.html)
- [ESPRESSO_Real-Time_v2_Averages_Best](http://tds.marine.rutgers.edu/thredds/dodsC/roms/espresso/2013_da/avg/ESPRESSO_Real-Time_v2_Averages_Best.html)

I believe that `ESPRESSO_Real-Time_v2_Averages_Best` is more adequate for this task.

---
For Southern California 3km ROMS YiChao I was browsing http://sccoos-obs0.ucsd.edu/thredds/catalog.html but that portal is timing our for me :-/

@rsignell-usgs can you help us sort this out? Do you know the preferred endpoints for those models?

**Comment by jbosch-noaa** [comment]
@dpsnowden  - Do you have a preference for which or all of the NECOFS model(s) @ocefpaf works with?
 
Is there a priority of which models he writes a notebook for now that the first notebook #303 is written and published?

**Comment by rsignell-usgs** [comment]
IOOS forecasts:
* Columbia River: http://amb6400b.stccmop.org:8080/thredds/catalog/model_data/catalog.html?dataset=model_data/forecast.nc
* OSU ROMS: http://ona.coas.oregonstate.edu:8080/thredds/catalog.html?dataset=OCOS
* CBOFS: https://opendap.co-ops.nos.noaa.gov/thredds/catalog/CBOFS/fmrc/catalog.html?dataset=CBOFS/fmrc/Aggregated_7_day_CBOFS_Fields_Forecast_best.ncd
* the 3km Southern California forecast model by Yi Chao is now at 
http://west.rssoffice.com:8080/thredds/catalog/roms/CA3km-forecast/CA/catalog.html
but although this is THREDDS, there is no Forecast Model Run Collection.  I will ping them and see if they are willing to add.  (I helped them with this before).

**Comment by ocefpaf** [comment]
First prototype for the grids: http://nbviewer.jupyter.org/gist/ocefpaf/5e5059ee6a73a32105bccf72249a0690

**Comment by ocefpaf** [comment]
We created 3 notebooks for this issue. Let's move this effort to #348
