### ISSUE TITLE
Website changes for alignment with ioos.us sites

### ISSUE THREAD

**Issue by MathewBiddle** [ioos/notebooks_demos#369]
- [ ] Add a standardized, centered IOOS header/masthead logo that links back to ioos.us
- [ ] menu bar logo: change link from ioos.github.io/notebooks_demos to ioos.us
- [x] footer: standardize to ioos.us design, add link to ioos.noaa.gov, contact info etc. Should have consistent look and feel if possible and match the content at the main ioos.us page

**Comment by mwengren** [comment]
@MathewBiddle I'll add, if there's a plan to rethink the rendering engine or template for this site, these changes can be made in whatever that ends up being, rather than try to fit them in before the change is made.  In other words, this issue can fit into the bigger picture considerations/schedule for the Notebook Gallery.

**Comment by ocefpaf** [comment]
@lohithmunakala let's drop the menu bar option. But do you think you can do the first one ("Add a standardized, centered IOOS header/masthead logo that links back to ioos.us")?

**Comment by lohithmunakala** [comment]
I actually did try that out, but we don't have the option to add links to anything other than the `.md /.ipynb` files.

I did add ioos.us to the footer of the menu bar. 

#### Basically IOOS - in blue.

![image](https://user-images.githubusercontent.com/56470584/127226726-d6268703-3c36-4dbc-b44b-42f0580148a8.png)

Is this fine?

**Comment by MathewBiddle** [comment]
I think we've done the best we can with the capability JupyterBook provides. Closing.

@mwengren we were able to remove the Copyright!
