### ISSUE TITLE
Error when running IOOS envrionment.yml 

### ISSUE THREAD

**Issue by mwengren** [ioos/notebooks_demos#95]
I'm trying to set up the IOOS environment using the environment.yml file as described (here)[https://github.com/ioos/notebooks_demos/wiki/Installing-Conda-Python-with-the-IOOS-environment].  

I've tried in both Anaconda2 and Anaconda3, and it gets to the step of configuring hdf5 and errors out.  Here are the errors:

Anaconda2:
```
nb_conda_kerne 100% |###############################| Time: 0:00:00   2.06 MB/s
_nb_ext_conf-0 100% |###############################| Time: 0:00:00 461.98 kB/s
nb_conda-2.0.0 100% |###############################| Time: 0:00:00   2.42 MB/s
Extracting packages ...
[      COMPLETE      ]|##################################################| 100%
Linking packages ...
Using Anaconda Cloud api site https://api.anaconda.org                   |   7%
Using Anaconda Cloud api site https://api.anaconda.org
Error: ERROR: placeholder 'C:/conda/envs/_build' too short in: hdf5-1.8.17-vc10_6
```

Anaconda3:
```
nb_anacondaclo 100% |###############################| Time: 0:00:00   3.37 MB/s
nb_conda-2.0.0 100% |###############################| Time: 0:00:00   1.27 MB/s
dask-0.11.0-py 100% |###############################| Time: 0:00:00   5.32 MB/s
distributed-1. 100% |###############################| Time: 0:00:00   6.42 MB/s
Extracting packages ...
[      COMPLETE      ]|##################################################| 100%
Unlinking packages ...
[      COMPLETE      ]|##################################################| 100%
Linking packages ...
PaddingError: Placeholder of length '20' too short in package conda-forge::hdf5-1.8.17-vc14_6.
The package must be rebuilt with conda-build > 2.0.
```

How can this be resolved?

**Comment by ocefpaf** [comment]
@mwengren the [CIs are passing](https://ci.appveyor.com/project/ocefpaf/notebooks-demos/build/1.0.57#L235) the env creation so maybe the problem is that you have an `environment.yml`. Please check if your file has the following lines like this one: https://github.com/ioos/notebooks_demos/blob/master/environment.yml#L3-L5

The problem is that `conda-forge` is, unfortunately, using `conda-build 1` (and will for a while since I lost the motion to upgrade it there :unamused:). Re-building the packages with `conda-build 2` fixes the issue and that is why I "resurrected" the old `IOOS` channel and added the broken packages there.

Here is what I recommend you to do:

- in your root environment issue a `conda update --all --yes`
- it looks like you do not have showe channels set so let's enable that too to be able to debug what is going on: `conda config --set show_channel_urls yes`
- now repeat the installation instructions with the latest [`environment.yaml`](https://raw.githubusercontent.com/ioos/notebooks_demos/master/environment.yml)

Let me know how that goes.

Ping @rsignell-usgs and @jbosch-noaa who also use Windows and manged to install this without a problem.

**Comment by mwengren** [comment]
I have a few different environments going at the same time.  The first is a slightly older Anaconda2 that I downloaded/installed several months ago.  The second is a freshly-downloaded Anaconda3 from yesterday.

I tried to follow the directions in the wiki for IOOS environment setup with both, and downloaded environment.yml fresh yesterday, but ended up at the errors above in each, although maybe at different steps.  

In the case of the Anaconda 2 environment, I don't think the ```conda update --all --yes``` step ever fully completed.  I will try again.  I went ahead and tried to create the IOOS environment anyway, when I encountered the above error. 

For Anaconda3, I got the hdf5 package error during the ```conda update --all --yes``` step, which errored out and didn't complete.   I also noticed that the jupyter and conda commands were not installed properly in my Anaconda3 install, so I may have separate issues with that.  They were not included in the /Scripts directory as they were in Anaconda2.  Not sure if that is expected or not for Anaconda3.

I'll continue to troubleshoot.

**Comment by ocefpaf** [comment]
> For Anaconda3, I got the hdf5 package error during the `conda update --all --yes`

Did you issue that command from the root env? If so that means you have packages in your root env that should not be there. Conda design works better when you leave the root env intact, only updating it every now and then, and installing packages in user envs, like the `IOOS` env for example. That ensures you do not contaminate the root env and that the activation hooks, that in some cases are needed to get the full functionality of a certain package, will work.

If you want we can try to debug this over a call.

**Comment by rsignell-usgs** [comment]
I think maybe our windows instructions are flawed.    I *never* check the boxes when I install, so I avoid getting stuff stuck into my path except when I run the Anaconda prompt.    Also `conda install console_shortcut` is no longer needed, as it's part of miniconda now.  

You might take a look at your windows path to see how many pythons are in there and remove them.  
I use the very handy free "rapid environment editor" http://www.rapidee.com/en/about  to edit my path -- it separates the path into separate entries you can edit so you don't have to work with a big huge text string.

**Comment by mwengren** [comment]
I believe I did, because that step comes before the step to set up the IOOS environment in the directions:
```
conda config --add channels conda-forge --force
conda update --yes --all
conda env create environment.yml
```
I'm not sure what packages I might have in my root env that shouldn't be there, because it was a fresh install.  Maybe it does not work with Anaconda?  Should I go to miniconda?  Have not tried that yet.

Another strange thing is that the activate/deactivate commands are not available in either 2 or 3, but I'm not sure if those are part of the standard Anaconda distribution or at what point in the above steps they should be enabled.
 
```
$ python --version
Python 2.7.11 :: Anaconda 2.5.0 (64-bit)
$ activate
bash: activate: command not found
```

**Comment by ocefpaf** [comment]
> I think maybe our windows instructions are flawed. I never check the boxes when I install, so I avoid getting stuff stuck into my path except when I run the Anaconda prompt.

@jbosch-noaa and I made the decision to ask to check the box, and warn about other Python instalations, it because most non-power users have less trouble that way.

> Also conda install console_shortcut is no longer needed, as it's part of miniconda now.

Again, it does not hurt to leave it there as people with old installations will need it. There is no error message if the shortcut already exist.

> I'm not sure what packages I might have in my root env that shouldn't be there

@mwengren if `hdf5` was a problem during the `update --all` command you either are updating an env or you have `hdf5` in your root env. I made assumptions in https://github.com/ioos/notebooks_demos/issues/95#issuecomment-255086361 b/c I do not know.

But if you issue the `update` command in the env that may be trying to get `hdf5` from conda-forge, which is the broken one. You can try to remove that env and try again.

> bash: activate: command not found

Wait. Bash!? Where are you installing this?

**Comment by mwengren** [comment]
I am using git bash with my own .bash_profile environment config overriding the windows environment settings.  So I am pre-pending things like python path that i want to use.  I have one environment for Ananconda2 and one for Anaconda3, with path overrides like so:

$ANACONDA3_HOME:$ANACONDA3_HOME\\Scripts:$ANACONDA3_HOME\\Library\\bin

This seems to work better for Anaconda2 as I can run jupyter notebook, etc, but not in 3 as of yet.  Maybe I'm missing some paths...

Unfortunately I have no control over the Windows environment (hooray, IT security policy!).

**Comment by ocefpaf** [comment]
> I am using git bash

Never tried anaconda/miniconda with `git-bash`. But the `activate`/`deactivate` are Windows commands. on `bash` they `source activate`/`source deactivate`. But I have no idea how anaconda/miniconda should work on git-bash.

PS: I did try Windows 10 bash, but there I followed the instructions like if it was a Linux machine and everything worked just fine.

**Comment by mwengren** [comment]
Ah, good point.  I do have a bit of a Frankenstein environment.  I never heard of Windows 10 bash before... maybe I can try that, although I enjoy the git-bash quite a bit.

I guess I do have hdf5 in the root environment (ie under /pkgs dir?), but I think that must have been installed during the ```conda update --yes --all``` step.  Should there be a step before that to create an 'IOOS' environment and then run those commands, or did I miss something?

**Comment by ocefpaf** [comment]
> Should there be a step before that to create an 'IOOS' environment and then run those commands, or did I miss something?

I do not know that what comes with Anaconda so maybe it was there before. BTW that is why I recommend `miniconda`, to avoid installing packages you will never use. Still, the env creation should work regardless of that failed update...

> I enjoy the git-bash quite a bit.

Then you will like the actual bash even more. It is a full Linux shell, ubuntu based, on Windows. See http://www.howtogeek.com/249966/how-to-install-and-use-the-linux-bash-shell-on-windows-10

**Comment by mwengren** [comment]
> http://www.howtogeek.com/249966/how-to-install-and-use-the-linux-bash-shell-on-windows-10

:( thanks, unfortunately one of those steps requires admin rights (which we are denied here).  I think I'm stuck trying to make this work with git-bash, but I'll troubleshoot further

**Comment by mwengren** [comment]
@ocefpaf I can report that the IOOS environment works as expected with both Miniconda 2 and 3 and git-bash, but there appear to be package version inconsistencies between the Anaconda default channels and the conda-forge channel (for hdf5 at least), so when you try to perform the conda update -all step it will error out (at least in my case after several attempts).  Here are the issues with the hdf5 package:
```
The following packages will be downloaded:
package                    |            build
 hdf5-1.8.17                |           vc14_6        12.4 MB  conda-forge
...
The following packages will be updated:
hdf5:            1.8.15.1-vc14_4                [vc14] --> 1.8.17-vc14_6      conda-forge [vc14]
```
Then the error I listed above occurs during the linking phase.  Fixing that is above my pay grade, so I'll stick with Miniconda.

**Comment by ocefpaf** [comment]
> but there appear to be package version inconsistencies between the Anaconda default channels and the conda-forge channel 

There are many more in fact :smile: full consistency between the two channels will take a while. From the `conda-forge`'s side we need to move to `conda-build 2`, and from Continuum's side they need to start building `defaults` packages using the stable version of `conda-forge` recipes. The former should be completed by the end of the year (hopefully before). The latter mat never happen...
